version: '3'

networks:
    hyperf-network:
        driver: bridge

services:

#hyperf-db
    hyperf-db:
        image: mysql:5.7
        container_name: hyperf-db
        restart: always
        ports:
            - "40006:3306"
        environment:
            MYSQL_DATABASE: hyperf
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Taipei
        command: [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--innodb-use-native-aio=0",
            "--server-id=1",
            "--log_bin=ON",
            "--default-authentication-plugin=mysql_native_password"
        ]
        volumes:
            - ./dockerize/data/mysql:/var/lib/mysql
        networks:
            - hyperf-network

#hyperf-redis
    hyperf-redis:
        image: redis:latest
        container_name: hyperf-redis
        restart: always
        volumes:
            - ./dockerize/data/redis:/data
        ports:
            - "40009:6379"
        environment:
            - TZ=Asia/Taipei
            - LANG=en_US.UTF-8
        logging:
          driver: "json-file"
          options:
            max-size: "1m"
        networks:
            - hyperf-network

#phpMyAdmin
    pma:
        image: phpmyadmin/phpmyadmin:latest
        container_name: hyperf-pma
        restart: always
        volumes:
            - ./dockerize/conf/phpMyAdmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        ports:
            - "40010:80"
        environment:
            SESSION_TIMEOUT: 86400
            PMA_HOST: hyperf-db
        networks:
            - hyperf-network
        depends_on:
            - hyperf-db

#phpRedisAdmin
    pra:
        image: erikdubbelboer/phpredisadmin:latest
        container_name: hyperf-pra
        restart: always
        ports:
            - "40011:80"
        environment:
            REDIS_1_HOST: hyperf-redis
            REDIS_1_NAME: hyperf-redis
        networks:
            - hyperf-network
        depends_on:
            - hyperf-redis

#hyperf
    hyperf:
        build:
            context: .
            dockerfile: ./dockerize/dockerfile/hyperf.dockerfile
            args:
                SW_VERSION: v4.5.11
                COMPOSER_VERSION: 2.0.9
        image: danielhuang030/hyperf:0.0.2
        container_name: hyperf
        restart: always
        ports:
          - "40000:9501"
          - "40001:9502"
        volumes:
          - "./hyperf:/app"
          - "./dockerize/conf/supervisord/supervisord.conf:/etc/supervisord.conf"
          - "./dockerize/log/hyperf/out.log:/var/log/hyperf-out.log"
          - "./dockerize/conf/php/php.ini:/etc/php7/conf.d/php-custom.ini"
        networks:
            - hyperf-network
        depends_on:
            - hyperf-db
            - hyperf-redis
