version: '3.7'

networks:
    hyperf-network:
        driver: bridge

services:

#hyperf-db
    hyperf-db:
        image: mysql:5.7
        container_name: ${DB_HOST:-hyperf-db}
        restart: always
        ports:
            - "${DB_PORT:-40006}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-hyperf}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
            TZ: ${TZ:-Asia/Taipei}
        command: [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--innodb-use-native-aio=0",
            "--server-id=1",
            "--log_bin=ON",
            "--default-authentication-plugin=mysql_native_password"
        ]
        volumes:
            - ./dockerize/data/mysql:/var/lib/mysql
        networks:
            - hyperf-network

#hyperf-redis
    hyperf-redis:
        image: redis:latest
        container_name: ${REDIS_HOST:-hyperf-redis}
        restart: always
        volumes:
            - ./dockerize/data/redis:/data
        ports:
            - "${REDIS_PORT:-40009}:6379"
        environment:
            - TZ=${TZ:-Asia/Taipei}
            - LANG=en_US.UTF-8
        logging:
          driver: "json-file"
          options:
            max-size: "1m"
        networks:
            - hyperf-network

#phpMyAdmin
    pma:
        image: phpmyadmin/phpmyadmin:latest
        container_name: hyperf-pma
        restart: always
        volumes:
            - type: bind
              source: ./dockerize/conf/phpMyAdmin/config.user.inc.php
              target: /etc/phpmyadmin/config.user.inc.php
        ports:
            - "${PMA_PORT:-40010}:80"
        environment:
            SESSION_TIMEOUT: ${PMA_SESSION_TIMEOUT:-86400}
            PMA_HOST: ${DB_HOST:-hyperf-db}
        networks:
            - hyperf-network
        depends_on:
            - ${DB_HOST:-hyperf-db}

#phpRedisAdmin
    pra:
        image: erikdubbelboer/phpredisadmin:latest
        container_name: hyperf-pra
        restart: always
        ports:
            - "${PRA_PORT:-40011}:80"
        environment:
            REDIS_1_HOST: hyperf-redis
            REDIS_1_NAME: hyperf-redis
        networks:
            - hyperf-network
        depends_on:
            - hyperf-redis

#hyperf-app
    hyperf-app:
        build:
            context: .
            dockerfile: ./dockerize/dockerfile/hyperf.dockerfile
            args:
                SW_VERSION: ${SW_VERSION:-v4.5.7}
                COMPOSER_VERSION: ${COMPOSER_VERSION:-2.0.2}
        image: danielhuang030/hyperf:0.0.3
        container_name: ${APP:-hyperf-app}
        restart: always
        ports:
          - "${SWOOLE_WEB_PORT:-40000}:9501"
          - "${SWOOLE_WEBSOCKET_PORT:-40001}:9502"
        volumes:
          - ./app:/app
          - ./dockerize/log/hyperf:/var/log
          - type: bind
            source: ./dockerize/conf/supervisord/supervisord.conf
            target: /etc/supervisord.conf
          - type: bind
            source: ./dockerize/conf/php/php.ini
            target: /etc/php7/conf.d/php-custom.ini
        networks:
            - hyperf-network
        depends_on:
            - ${DB_HOST:-hyperf-db}
            - ${REDIS_HOST:-hyperf-redis}
